[Interface]
PrivateKey = mGrfpYudrssAgxVCUEbhixGb0CU41aElLc03tQiyIHI=
Address = 10.88.247.2/24,fd11:5ee:bad:c0de::a58:f702/64
DNS = 9.9.9.9, 149.112.112.112

[Peer]
PublicKey = H2sdKfkUnP6vGK0PnD6IlIvjYLLdELXMbB6bjwEskm8=
PresharedKey = LsnE3HquG10bcw2bN1jsUNUEELFITtZmer0ClJy9MX8=
Endpoint = 72.61.192.44:51820
AllowedIPs = 0.0.0.0/0, ::0/0
